# This is a config for E2B sandbox template.
# You can use template ID (e4nnvf5waleuwcr3aqna) or template name (vibe-coder-vivekg) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-coder-vivekg") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-coder-vivekg") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-coder-vivekg')

team_id = "af9aadb9-537b-4aad-9927-53e458d47bcb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-coder-vivekg"
template_id = "e4nnvf5waleuwcr3aqna"
