# This is a config for E2B sandbox template.
# You can use template ID (ny0p8va3dih09ad9ogff) or template name (vibe-coder-vivekg2005) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-coder-vivekg2005") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-coder-vivekg2005") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-coder-vivekg2005')

team_id = "af9aadb9-537b-4aad-9927-53e458d47bcb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-coder-vivekg2005"
template_id = "ny0p8va3dih09ad9ogff"
